//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment25
{
    using System;
    
    public partial class ctlTweet
    {
        public int TweetId { get; set; }
        public int TweetUserId { get; set; }
        public string TweetText { get; set; }
        public System.DateTime TweetModifiedDate { get; set; }
        public bool TweetDeleted { get; set; }
    }
}
