//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment25
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTweet
    {
        public int TweetId { get; set; }
        public int TweetUserId { get; set; }
        public string TweetText { get; set; }
        public Nullable<System.DateTime> TweetModifiedDate { get; set; }
        public Nullable<bool> TweetDeleted { get; set; }
        public string TweetUserName { get; set; }
    
        public virtual TblTweetuser TblTweetuser { get; set; }
    }
}
